import { describe, it, expect } from "vitest";
import * as fs from "fs";
import * as path from "path";
import { extractTokens } from "../../scripts/crawler/token_extractor";

describe("Stage 1: Token Extractor Validator (Live Captured Data)", () => {
  it("parses live W3C DTCG payload generated by the Playwright crawler", () => {
    const liveCapturePath = path.resolve(
      __dirname,
      "../../mock_capture/01_design_tokens.json",
    );
    const captureData = JSON.parse(fs.readFileSync(liveCapturePath, "utf-8"));

    // Extractor should easily parse the `{ $value: ..., $type: ... }` format
    const semanticTokens = extractTokens(captureData);

    // The live data contains "#E24A4A" for primary
    // It should be converted to raw rgb string natively
    expect(semanticTokens.cssVariables["--primary"]).toBe("226 74 74"); // #E24A4A -> 226, 74, 74

    // The live data contains "#FFFFFF" for background
    expect(semanticTokens.cssVariables["--background"]).toBe("255 255 255");

    // Check typography parsing (e.g. `fontFamily.sans`)
    expect(semanticTokens.cssVariables["--font-sans"]).toBe(
      "Inter, sans-serif",
    );
  });
});
