import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { runIntakeQueue } from "../../src/crawler/queue";
import * as capture from "../../src/crawler/capture";
import { setConfig, getConfig } from "../../src/config";
import * as fs from "fs/promises";
import * as path from "path";
import * as os from "os";

describe("Crawler Queue", () => {
  let tempDir: string;
  let csvPath: string;
  let outputDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "fotocopy-queue-test-"));
    csvPath = path.join(tempDir, "intake.csv");
    outputDir = path.join(tempDir, "output");
    await fs.mkdir(outputDir, { recursive: true });

    const originalConfig = getConfig();
    setConfig({
      ...originalConfig,
      intakeCsvPath: csvPath,
      outputDir: outputDir,
    });

    vi.spyOn(capture, "crawlAndCapture").mockImplementation(async () => {});
    vi.spyOn(console, "log").mockImplementation(() => {});
    vi.spyOn(console, "error").mockImplementation(() => {});
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
    vi.restoreAllMocks();
  });

  it("throws error if CSV path is missing", async () => {
    setConfig({ outputDir });
    await expect(runIntakeQueue()).rejects.toThrow(
      "Missing CSV path in config generated by fotocopy.",
    );
  });

  it("throws error if outputDir is missing", async () => {
    setConfig({ intakeCsvPath: csvPath });
    await expect(runIntakeQueue()).rejects.toThrow("Missing outputDir");
  });

  it("reads CSV and dispatches capture logic correctly", async () => {
    const csvData = "url\nhttp://mock.com/page1\nhttp://mock.com/page2\n";
    await fs.writeFile(csvPath, csvData);

    await runIntakeQueue();

    expect(capture.crawlAndCapture).toHaveBeenCalledTimes(2);
    expect(capture.crawlAndCapture).toHaveBeenNthCalledWith(1, {
      url: "http://mock.com/page1",
      outputDir,
    });
    expect(capture.crawlAndCapture).toHaveBeenNthCalledWith(2, {
      url: "http://mock.com/page2",
      outputDir,
    });
  });

  it("gracefully catches and logs individual crawl errors without crashing entire queue", async () => {
    const csvData =
      "url\nhttp://mock.com/success\nhttp://mock.com/fail\nhttp://mock.com/success2\n";
    await fs.writeFile(csvPath, csvData);

    vi.spyOn(capture, "crawlAndCapture").mockImplementation(async ({ url }) => {
      if (url === "http://mock.com/fail") throw new Error("DOM Crash");
    });

    await runIntakeQueue();

    expect(capture.crawlAndCapture).toHaveBeenCalledTimes(3);
    expect(console.error).toHaveBeenCalledWith(
      "Failed to ingest http://mock.com/fail:",
      expect.any(Error),
    );
  });
});
