import * as fs from "fs/promises";
import { crawlAndCapture } from "./capture";
import { getConfig } from "../config";

// Phase 1, Step 5: URL Discovery
export async function runIntakeQueue() {
  const csvPath = getConfig().intakeCsvPath;
  if (!csvPath)
    throw new Error("Missing CSV path in config generated by fotocopy.");
  const outputDir = getConfig().outputDir;
  if (!outputDir) throw new Error("Missing outputDir");

  console.log(`Reading Intake CSV at: ${csvPath}`);
  const csvContent = await fs.readFile(csvPath, "utf-8");

  // Very basic CSV parser
  const lines = csvContent.split("\n").filter((l) => l.trim() !== "");
  lines.shift(); // remove header

  const urls = lines.map((line) => line.trim());
  console.log(`Found ${urls.length} URLs in queue.`);

  for (const url of urls) {
    console.log(`\n===================`);
    console.log(`Orchestrating crawl for: ${url}`);
    try {
      await crawlAndCapture({ url, outputDir });
      console.log(`Success: Target completed.`);
    } catch (err) {
      console.error(`Failed to ingest ${url}:`, err);
    }
  }

  console.log(`\n===================`);
  console.log(
    `Intake Queue complete! Phase 1 Orchestrator successfully finished.`,
  );
}

/* v8 ignore start */
if (require.main === module) {
  runIntakeQueue();
}
